version: '3'

services:
  web:
    build:
      context: .
      dockerfile: support/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cache:/app/.cache
      - public:/app/public
      - yarn_cache:/usr/local/share/.cache/yarn/v4
    ports:
      - '19336:19336'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      PORT: '19336'
    command: 'sh ./support/start.sh'

volumes:
  node_modules:
  cache:
  public:
  yarn_cache:
